export const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER'
export const DELETE_PLAYER = "DELETE_PLAYER"
export const CHOOSE_MODE = 'CHOOSE_MODE'
export const GET_RANDOM_QUESTION = 'GET_RANDOM_QUESTION'
export const GET_RANDOM_ACTION = 'GET_RANDOM_ACTION'